FROM node:12-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json package-lock.json /app/
RUN npm install --silent
RUN npm install @vue/cli@3.7.0 -g
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
COPY . /app
