name: Lint and deploy PR demo to Pages

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout PR
        with:
          persist-credentials: false

      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install

      - name: Lint
        run: |
          npm run lint
          npm run lint:style

      - name: Build
        run: |
          export BASE_URL=/zakyat-frontend/${{ github.event.number }}/
          npm run generate

      - name: Move output files to a folder with PR number
        run: |
          mkdir demo
          mv dist/ demo/${{ github.event.number }}

      - name: Deploy demo to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: demo
          keep_files: true

      - name: Post demo URL on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Demo available on https://zakyat.github.io/zakyat-frontend/${{ github.event.number }}/"
